### ISSUE TITLE
A new Software developer team

### ISSUE THREAD

**Issue by wumpus27** [MitkoVtori/Message-me#2]
Hello.

Do you want to join my organization for creating apps (with .NET and C#), websites and more? I would be happy, when you like to join me and be a team with me (then you are my first programmer friend in my life …)???

**Comment by MitkoVtori** [comment]
I don't know .NET or C# at all. I can create websites with html, css and JavaScript.

**Comment by wumpus27** [comment]
This is also okay. You can join my organization and you can make awesome websites with (or when you want to do it alone, without me) me. Thank you very much. I'll contact you via other methods tomorrow.

**Comment by SnepalDelaupe** [comment]
@github-host2 Hi, I'm @MitkoVtori's friend. He told me he had to go somewhere, so he would'nt be able the next 3 days. He doesn't have access to his computer but he say he'll message you Sunday. Have a great week!

**Comment by wumpus27** [comment]
@SnepalDelaupe Thank you very much.
